# Generated by Django 4.2.4 on 2023-09-30 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=50)),
                ('des', models.TextField()),
                ('ingredient', models.TextField()),
                ('image', models.FileField(upload_to='static/product/')),
                ('category', models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.CASCADE, to='onlinestore.category')),
            ],
        ),
    ]
