# Generated by Django 4.2.4 on 2023-10-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0002_alter_product_price_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='cart', max_length=100),
        ),
    ]
