# Generated by Django 4.2.4 on 2023-10-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0011_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.IntegerField(),
        ),
    ]
