# Generated by Django 4.2.4 on 2023-10-27 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlinestore', '0012_alter_postlike_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='product',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconduser', models.IntegerField(unique=True)),
                ('status', models.CharField(default='follow', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
