# Generated by Django 4.2.4 on 2023-10-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0016_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
