# Generated by Django 4.2.4 on 2023-11-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0019_profile_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile_page',
        ),
    ]
