# Generated by Django 4.2.4 on 2023-11-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0022_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.FileField(default='static/image/profile.jp', upload_to='static/image'),
        ),
    ]
